version: '3.8'

services:
  kong-gw:
    image: kong/kong-gateway:3.6.1.1
    volumes:
      - '${PWD}:/Users/tharindusenevirathna/Kong/'
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/Users/tharindusenevirathna/Kong/kong.yml'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_ADMIN_GUI_URL: 'http://localhost:8002' 
    ports:
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
      - '8444:8444'
      - '8002:8002'
      - '8445:8445'
      - '8003:8003'
      - '8004:8004'
    restart: on-failure
    networks:
      - default-network

  joke-service:
    image: joke-service:1.0.0
    depends_on:
      - mysql-db
    restart: on-failure
    networks:
      - default-network

  submitter-service:
    image: submitter-service:1.0.0
    restart: on-failure
    networks:
      - default-network

  moderator-service:
    image: moderator-service:1.0.0
    depends_on:
      - mysql-db
    restart: on-failure
    networks:
      - default-network

  analyze-service:
    image: analyze-service:1.0.0
    depends_on:
      - mongo-db
    restart: on-failure
    networks:
      - default-network

  etl-service:
    image: etl-service:1.0.0
    depends_on:
      - mysql-db
      - mongo-db
    restart: on-failure
    networks:
      - default-network

  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'diamondback'
    command: --default-authentication-plugin=mysql_native_password
    depends_on:
      - kong-gw
    restart: on-failure
    networks:
      - default-network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - default-network

  rabbbit-mq:
    image: rabbitmq:3-management
    ports:
      - '8080:15672'
      - '5672:5672'
    restart: on-failure
    networks:
      - default-network
      
networks:
  default-network:
    driver: bridge