version: '3.8'

services:
  kong-gw:
    image: kong/kong-gateway:3.6.1.1
    volumes:
      - '${PWD}:/home/OsAdmin/project'
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: '/home/OsAdmin/project/kong.yml'
      KONG_PROXY_ACCESS_LOG: '/dev/stdout'
      KONG_ADMIN_ACCESS_LOG: '/dev/stdout'
      KONG_PROXY_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_ERROR_LOG: '/dev/stderr'
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_ADMIN_GUI_URL: 'http://172.191.226.20:8002' # kong ip
    ports:
      - '80:8000'
      - '8443:8443'
      - '8001:8001'
      - '8444:8444'
      - '8002:8002'
      - '8445:8445'
      - '8003:8003'
      - '8004:8004'
    restart: on-failure
    networks:
      - api-gw-network
      
networks:
  api-gw-network:
    driver: bridge