version: '3.8'

services:
  analytics-service:
    image: analytics-service:1.0.0
    environment:
      SERVICE_NAME: 'ANALYTICS SERVICE'
      BASE_URL: '10.1.0.4' # analytics ip
      MONGO_ROOT_PASSWORD: 'diamondback'
      MONGO_CONTAINER_PORT: 4302
      PORT: 3300
    depends_on:
      - mongo
    restart: on-failure
    ports:
      - '4300:3300'
    networks:
      - analytics-service-network

  analytics-etl-service:
    image: etl-service:1.0.0
    environment:
      SERVICE_NAME: 'ANALYTICS ETL SERVICE'
      BASE_URL: '10.1.0.4' # analytics ip
      RMQ_URL: '10.0.0.6' # moderate ip
      MONGO_ROOT_PASSWORD: 'diamondback'
      MONGO_CONTAINER_PORT: 4302
      MOD_CONTAINER_PORT: 4101
      AN_QUEUE_NAME: 'LOGGED_JOKES_QUEUE'
      PORT: 3301
    depends_on:
      - mongo
    restart: on-failure
    ports:
      - '4301:3301'
    networks:
      - analytics-service-network

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: diamondback
    ports:
      - '4302:27017'
    networks:
      - analytics-service-network

networks:
  analytics-service-network:
    driver: bridge
