version: '3.8'

services:
  moderate-service:
    image: moderate-service:1.0.0
    environment:
      SERVICE_NAME: 'MODERATE SERVICE'
      GW_URL: 172.191.226.20 # gateway ip
      RMQ_SUBMIT_URL: '10.0.0.5' #submit ip
      RMQ_MODERATE_URL: '10.0.0.6' #moderate ip
      SM_QUEUE_NAME: 'SUBMITTED_JOKES_QUEUE'
      MOD_QUEUE_NAME: 'MODERATED_JOKES_QUEUE'
      AN_QUEUE_NAME: 'LOGGED_JOKES_QUEUE'
      SM_CONTAINER_PORT: 4201
      MOD_CONTAINER_PORT: 4101
      PORT: 3100
      GW_PORT: 80
      MYSQL_URL: 'mysql-db'
      MYSQL_ROOT_PASSWORD: 'diamondback'
      USERNAME: 'admin'
      PASSWORD: 'diamondback'
      JWT_SECRET: 'a0ujCO72Vy4tn7t828uQ'
    depends_on:
      - mysql-db
    restart: on-failure
    ports:
      - '4100:3100'
    networks:
      - moderate-service-network

  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'diamondback'
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    networks:
      - moderate-service-network

  rabbbit-mq:
    image: rabbitmq:3-management
    ports:
      - '4102:15672'
      - '4101:5672'
    restart: on-failure
    networks:
      - moderate-service-network

networks:
  moderate-service-network:
    driver: bridge
