version: '3.8'

services:
  moderator-service:
    image: moderator-service:1.0.0
    environment:
      RMQ_SUBMITTER_URL: '20.186.38.219' #submitter ip
      RMQ_MODERATOR_URL: '20.186.39.3' #moderator ip
      SM_QUEUE_NAME: 'SUBMITTED_JOKES_QUEUE'
      MOD_QUEUE_NAME: 'MODERATED_JOKES_QUEUE'
      AN_QUEUE_NAME: 'LOGGED_JOKES_QUEUE'
      SM_CONTAINER_PORT: 4201
      MOD_CONTAINER_PORT: 4101
      PORT: 3100
      MYSQL_URL : 'mysql-db'
      MYSQL_ROOT_PASSWORD : 'diamondback'
      USERNAME: 'admin'
      PASSWORD: 'diamondback'
      JWT_SECRET: 'a0ujCO72Vy4tn7t828uQ'
    depends_on:
      - mysql-db
    restart: on-failure
    ports:
      - '4100:3100'
    networks:
      - moderator-service-network

  mysql-db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'diamondback'
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    networks:
      - moderator-service-network

  rabbbit-mq:
    image: rabbitmq:3-management
    ports:
      - '4102:15672'
      - '4101:5672'
    restart: on-failure
    networks:
      - moderator-service-network
      
networks:
  moderator-service-network:
    driver: bridge